(function_declaration name: (identifier) @definition.function)
(generator_function_declaration name: (identifier) @definition.function)
(class_declaration name: (type_identifier) @definition.class)
(interface_declaration name: (type_identifier) @definition.interface)
(type_alias_declaration name: (type_identifier) @definition.type)
(enum_declaration name: (identifier) @definition.enum)
(method_definition name: (property_identifier) @definition.method)
(variable_declarator name: (identifier) @definition.variable)
(import_specifier name: (identifier) @definition.import)
(import_specifier alias: (identifier) @definition.import)
(import_clause (identifier) @definition.import)
(namespace_import (identifier) @definition.import)
