use std::{
    env, fs,
    path::PathBuf,
    process::{Command, Output},
    sync::atomic::Ordering,
    time::{SystemTime, UNIX_EPOCH},
};

use super::{FIXTURE_COUNTER, write_commit, write_file, write_tree};

impl MapFixtureRepository {
    pub(crate) fn new() -> Self {
        let suffix = format!(
            "dalil-map-{}-{}",
            std::process::id(),
            FIXTURE_COUNTER.fetch_add(1, Ordering::Relaxed)
        );
        let temporary_root = env::temp_dir().join(suffix);
        let root = temporary_root.join("repository");
        let cache = temporary_root.join("xdg-cache");
        fs::create_dir_all(root.join("src")).expect("create map fixture source scope");
        fs::create_dir_all(&cache).expect("create map fixture cache");

        let tracked_files = [
            (".gitignore", "src/ignored.rs\n"),
            ("README.md", "source map fixture\n"),
            ("src/lib.rs", "pub fn parse() {}\n"),
            ("src/tracked_ignored.rs", "pub fn tracked() {}\n"),
            ("src/one.rs", "pub fn duplicate() {}\n"),
            ("src/two.rs", "pub fn duplicate() {}\n"),
            ("src/use.rs", "fn use_it() { duplicate(); }\n"),
            ("src/broken.rs", "fn broken( {\n"),
        ];
        let repository = gix::init(&root).expect("initialize map fixture repository");
        let tree = write_tree(&repository, &tracked_files);
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time is after the Unix epoch")
            .as_secs() as i64;
        let commit = write_commit(
            &repository,
            tree,
            &[],
            "Map Fixture",
            "map@example.com",
            now,
            "Initial source map fixture",
        );
        drop(repository);

        write_file(root.join(".git/HEAD"), b"ref: refs/heads/main\n");
        write_file(root.join(".git/refs/heads/main"), format!("{commit}\n").as_bytes());
        for (path, contents) in tracked_files {
            write_file(root.join(path), contents.as_bytes());
        }
        write_file(
            root.join("src/lib.rs"),
            b"pub fn parse() { let value = 1; let _ = value; }\n",
        );
        write_file(root.join("src/untracked.rs"), b"pub fn fresh() {}\n");
        write_file(root.join("src/ignored.rs"), b"pub fn ignored() {}\n");
        gix::open(&root).expect("open map fixture repository");

        Self { root, cache, temporary_root }
    }

    pub(crate) fn run(&self, arguments: &[&str]) -> Output {
        self.command(arguments).output().expect("run map fixture command")
    }

    pub(crate) fn command(&self, arguments: &[&str]) -> Command {
        let mut command = Command::new(env!("CARGO_BIN_EXE_dalil"));
        command
            .args(arguments)
            .current_dir(&self.root)
            .env("XDG_CACHE_HOME", &self.cache);
        command
    }
}

pub(crate) struct MapFixtureRepository {
    pub(crate) root: PathBuf,
    pub(crate) cache: PathBuf,
    pub(crate) temporary_root: PathBuf,
}

impl Drop for MapFixtureRepository {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.temporary_root);
    }
}

pub(crate) struct ClassificationFixtureRepository {
    pub(crate) root: PathBuf,
    pub(crate) cache: PathBuf,
    pub(crate) temporary_root: PathBuf,
}

impl ClassificationFixtureRepository {
    pub(crate) fn new() -> Self {
        let suffix = format!(
            "dalil-classification-{}-{}",
            std::process::id(),
            FIXTURE_COUNTER.fetch_add(1, Ordering::Relaxed)
        );
        let temporary_root = env::temp_dir().join(suffix);
        let root = temporary_root.join("repository");
        let cache = temporary_root.join("xdg-cache");
        fs::create_dir_all(root.join("src/vendor")).expect("create classification fixture source scope");
        fs::create_dir_all(root.join("vendor")).expect("create classification fixture vendor scope");
        fs::create_dir_all(root.join("target/debug/deps")).expect("create classification fixture build output");
        fs::create_dir_all(&cache).expect("create classification fixture cache");

        let large_generated = format!(
            "// Code generated by fixture. DO NOT EDIT.\npub fn generated() {{ {} }}\n",
            "let _ = 1; ".repeat(100_000)
        );
        let tracked_files = vec![
            (".gitignore", "target/\nvendor/\n".to_owned()),
            ("README.md", "classification fixture\n".to_owned()),
            (
                "Cargo.toml",
                "[package]\nname = \"fixture\"\nversion = \"0.1.0\"\n".to_owned(),
            ),
            ("src/lib.rs", "pub fn maintained() {}\n".to_owned()),
            ("src/main.rs", "fn main() { fixture::maintained(); }\n".to_owned()),
            (
                "src/generated_marker.rs",
                "// Code generated by fixture. DO NOT EDIT.\npub fn marker() {}\n".to_owned(),
            ),
            ("src/bundle.min.js", format!("const bundle={};", "x".repeat(1_200))),
            ("src/heuristic.js", format!("const heuristic={};", "x".repeat(1_200))),
            (
                "src/bundle.js.map",
                "{\"version\":3,\"sources\":[\"src/lib.ts\"]}\n".to_owned(),
            ),
            (
                "src/generated_parser.rs",
                "pub fn generated_parser() { let generated = 1; let _ = generated; }\n".to_owned(),
            ),
            ("src/vendor/tracked.rs", "pub fn vendored() {}\n".to_owned()),
            ("src/large.generated.rs", large_generated),
        ];
        let repository = gix::init(&root).expect("initialize classification fixture repository");
        let tree_files = tracked_files
            .iter()
            .map(|(path, contents)| (*path, contents.as_str()))
            .collect::<Vec<_>>();
        let tree = write_tree(&repository, &tree_files);
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time is after the Unix epoch")
            .as_secs() as i64;
        let commit = write_commit(
            &repository,
            tree,
            &[],
            "Classification Fixture",
            "classification@example.com",
            now,
            "Initial classification fixture",
        );
        drop(repository);
        write_file(root.join(".git/HEAD"), b"ref: refs/heads/main\n");
        write_file(root.join(".git/refs/heads/main"), format!("{commit}\n").as_bytes());
        for (path, contents) in &tracked_files {
            write_file(root.join(path), contents.as_bytes());
        }
        write_file(root.join("vendor/untracked.rs"), b"pub fn ignored_vendored() {}\n");
        for index in 0..256 {
            write_file(
                root.join(format!("target/debug/deps/artifact-{index:03}.json")),
                b"{}\n",
            );
        }
        #[cfg(unix)]
        std::os::unix::fs::symlink("artifact-000.json", root.join("target/debug/deps/artifact-link.json"))
            .expect("create ignored build-output symlink");
        gix::open(&root).expect("open classification fixture repository");

        Self { root, cache, temporary_root }
    }

    pub(crate) fn run(&self, arguments: &[&str]) -> Output {
        let mut command = Command::new(env!("CARGO_BIN_EXE_dalil"));
        command
            .args(arguments)
            .current_dir(&self.root)
            .env("XDG_CACHE_HOME", &self.cache);
        command.output().expect("run classification fixture command")
    }
}

impl Drop for ClassificationFixtureRepository {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.temporary_root);
    }
}
