(function_item name: (identifier) @definition.function)
(struct_item name: (type_identifier) @definition.struct)
(enum_item name: (type_identifier) @definition.enum)
(trait_item name: (type_identifier) @definition.trait)
(type_item name: (type_identifier) @definition.type)
(const_item name: (identifier) @definition.const)
(static_item name: (identifier) @definition.static)
(mod_item name: (identifier) @definition.module)
(macro_definition name: (identifier) @definition.macro)
(use_declaration argument: (identifier) @definition.import)
(use_declaration argument: (scoped_identifier name: (identifier) @definition.import))
(use_declaration argument: (use_as_clause alias: (identifier) @definition.import))
(use_declaration argument: (use_list (identifier) @definition.import))
(use_declaration argument: (scoped_use_list list: (use_list (identifier) @definition.import)))
(field_declaration name: (field_identifier) @definition.field)
